"""Create vendas schema and tables

Revision ID: 71ebb31ca68d
Revises: 
Create Date: 2024-08-29 18:50:42.570679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71ebb31ca68d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_stage_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('arquivo_original_registros', sa.Integer(), nullable=True),
    sa.Column('registros_apos_limpeza', sa.Integer(), nullable=True),
    sa.Column('registros_ignorados', sa.Integer(), nullable=True),
    sa.Column('data_fim', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='vendas'
    )
    op.create_table('stage_sales_data',
    sa.Column('data_venda', sa.DateTime(), nullable=True),
    sa.Column('numero_nota', sa.Integer(), nullable=True),
    sa.Column('codigo_produto', sa.CHAR(length=4), nullable=True),
    sa.Column('descricao_produto', sa.String(length=100), nullable=True),
    sa.Column('codigo_cliente', sa.CHAR(length=4), nullable=True),
    sa.Column('descricao_cliente', sa.String(length=100), nullable=True),
    sa.Column('valor_unitario_produto', sa.Numeric(), nullable=True),
    sa.Column('quantidade_vendida_produto', sa.Integer(), nullable=True),
    sa.Column('valor_total', sa.Numeric(), nullable=True),
    sa.Column('custo_da_venda', sa.Numeric(), nullable=True),
    sa.Column('valor_tabela_de_preco_do_produto', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('data_venda', 'numero_nota'),
    schema='vendas'
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_timestamp', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('log_level', sa.String(length=10), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('monitoring_stage_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['monitoring_stage_id'], ['vendas.monitoring_stage_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='vendas'
    )
    op.drop_table('alembic_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc')
    )
    op.drop_table('logs', schema='vendas')
    op.drop_table('stage_sales_data', schema='vendas')
    op.drop_table('monitoring_stage_data', schema='vendas')
    # ### end Alembic commands ###
